import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError('Unsupported platform for Firebase options.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FjYMOLWkOnymjLTCTI2PHtvRUU94WHQ',
    appId: '1:148688965299:web:ff0809642f9285ca7c2ac6',
    messagingSenderId: '148688965299',
    projectId: 'sunhack-1e794',
    authDomain: 'sunhack-1e794.firebaseapp.com',
    storageBucket: 'sunhack-1e794.firebasestorage.app',
    measurementId: 'G-6VGQZ9TXKC',
  );

  // Replace with values generated by `flutterfire configure`.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlBaIpQ3JTyBdQYgb_GUmbSU9PVsCZJv0',
    appId: '1:148688965299:android:150c2292e084ec1d7c2ac6',
    messagingSenderId: '148688965299',
    projectId: 'sunhack-1e794',
    storageBucket: 'sunhack-1e794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ucV0nbbSc9jj2SsV12B1Rx86oka5J2c',
    appId: '1:148688965299:ios:cefd4eaefeef22f57c2ac6',
    messagingSenderId: '148688965299',
    projectId: 'sunhack-1e794',
    storageBucket: 'sunhack-1e794.firebasestorage.app',
    androidClientId: '148688965299-qsgok8332iejv09c50bhqkhs5supbsmm.apps.googleusercontent.com',
    iosClientId: '148688965299-pghpvevvtu6nv1k2hj8hq0842u11gl94.apps.googleusercontent.com',
    iosBundleId: 'com.example.conflictsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ucV0nbbSc9jj2SsV12B1Rx86oka5J2c',
    appId: '1:148688965299:ios:cefd4eaefeef22f57c2ac6',
    messagingSenderId: '148688965299',
    projectId: 'sunhack-1e794',
    storageBucket: 'sunhack-1e794.firebasestorage.app',
    androidClientId: '148688965299-qsgok8332iejv09c50bhqkhs5supbsmm.apps.googleusercontent.com',
    iosClientId: '148688965299-pghpvevvtu6nv1k2hj8hq0842u11gl94.apps.googleusercontent.com',
    iosBundleId: 'com.example.conflictsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3FjYMOLWkOnymjLTCTI2PHtvRUU94WHQ',
    appId: '1:148688965299:web:c982ce12cc92abe87c2ac6',
    messagingSenderId: '148688965299',
    projectId: 'sunhack-1e794',
    authDomain: 'sunhack-1e794.firebaseapp.com',
    storageBucket: 'sunhack-1e794.firebasestorage.app',
    measurementId: 'G-JPTDV2BCZF',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );
}